MindfireSolutions/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MindfireSolutions.ViewModels;
using MindfireSolutions.Models;
using MindfireSolutions.UserModelContext;
using MindfireSolutions.BAL;
using System.Net.Mail;
using System.Net;
using System.Xml.Linq;
using System.Text.RegularExpressions;
using MindfireSolutions.BALInterface;

namespace MindfireSolutions.Controllers
{
    public class RegistrationController : Controller
    {
        private IUserRegisterBAL userRegisterBAL;

        public RegistrationController(IUserRegisterBAL _userRegisterBAL)
        {
            userRegisterBAL = _userRegisterBAL;
        }

        /// <summary>This action used for user register
        // GET: Registration
        public ActionResult Register()
        {
            return View();
        }

        /// <summary>This action used for user register
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Register(UserRegistration userAccount)
        {
            try
            {
                string message = "";
                bool status = false;
                if (!ModelState.IsValid)
                {
                    return View(userAccount);
                }
                using (UserAccountContext userDB = new UserAccountContext())
                {
                    if (userRegisterBAL.IsEmailExistBAl(userAccount) != null)
                    {
                        ViewBag.invalidEmailMessage = "Email id is already Exit";
                        return View(userAccount);
                    }
                    User userModel = userRegisterBAL.UploadUserData(userDB, userAccount);
                    if (userRegisterBAL.ContactValidation(userAccount) != 0)
                    {
                        ViewBag.ContactError = "Invalid input";
                        return View(userAccount);
                    }
                    userRegisterBAL.SendVerificationCode(userModel.Email, userModel.ActivationCode.ToString());
                    message = "Registered successfully done . Account Activation link " +
                        "has been sent to your email id : " + userModel.Email;
                    status = true;
                    ModelState.Clear();

                    ViewBag.successMessage = message;
                    ViewBag.status = status;

                }
                return View(userAccount);
            }
            catch (Exception exception)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
        }
        public ActionResult ValidateEmail()
        {
            return Json(userRegisterBAL.ValidateEmailBAl(Request["email"]));
        }
    }
}

MindfireSolutions/Views/Shared/ErrorView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ErrorView</title>
</head>
<body>
    <div>
        Something wrong
    </div>
</body>
</html>

MindfireSolutions/Views/Shared/UserLoginSignup.cshtml
<div class="tab-group">
    <span class="btn btn-outline-primary tag-signup"><a href="/Registration/Register">Sign Up</a></span>
    <span class="btn btn-outline-primary tag-login"><a href="/Login/UserLogin">Log In</a></span>
</div>

MindfireSolutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <meta name="description" content="User Registration Form">
    <link rel="shortcut icon" type="image/png" href="~/Images/mindfiresolutions@gmail.compexels-photo-248797.jpeg" />
    <link rel="shortcut icon" type="image/png" href="~/Images/santanu@gmail.comdownload.png" />
    <meta name="keywords" content="User Registration Form,Registration Form">
    <meta name="author" content="Purnendu Pattanaik">
    @using System.Web.Optimization
    @Styles.Render("~/bundles/styles")
    @Scripts.Render("~/bundles/scripts")
</head>

<body>
    <header class="container-fluid">
        <div class="header-one">
            <h1 class="header-font"><em><strong>User </strong>Registration</em></h1>
        </div>
    </header>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="glyphicon glyphicon-align-justify"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="/Login/UserLogout"> Logout</a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Log in & Sign up", "Register", "Registration")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <h5 class="container">
                &copy; Copyright
                <script>document.write(new Date().getFullYear());</script>
                all rights reserved
            </h5>
        </footer>
    </div>
</body>
</html>